### ISSUE TITLE
clang-asan container

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/containers#12]
It seems that we can use Ubuntu 22.04 for this, with clang-15 from the LLVM repo, and gfortran-12.

We can use R-devel with P3M R-release binaries.

We can compile base R _without_ ASAN support and link it _with_ ASAN support. This way base R is not slow because of the ASAN instrumentation, but packages can be ASAN instrumented (via the user's `Makevars`).

**Comment by gaborcsardi** [comment]
Seems like we don't need these checks:
```
* checking for .dll and .exe files ... OK
...
* checking for sufficient/correct file permissions ... OK
...
* checking installed package size ... OK
...
* checking DESCRIPTION meta-information ... OK
...
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
...
* checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking line endings in shell scripts ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking line endings in Makefiles ... OK
* checking compilation flags in Makevars ... OK
* checking for GNU extensions in Makefiles ... OK
* checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
* checking use of PKG_*FLAGS in Makefiles ... OK
* checking use of SHLIB_OPENMP_*FLAGS in Makefiles ... OK
* checking pragmas in C/C++ headers and code ... OK
* checking compilation flags used ... OK
...
* checking for unstated dependencies in ‘tests’ ... OK
...
* checking for non-standard things in the check directory ... OK
* checking for detritus in the temp directory ... OK
```

Plus skip the bashism test and building the vignettes.

**Comment by gaborcsardi** [comment]
Probably it is just `--extra-arch`.

**Comment by gaborcsardi** [comment]
Then we need to search for "AddressSanitizer" (?) in the example and test output files, and if it is included, then fail with a non-zero error code.

**Comment by dfalbel** [comment]
Hey @gaborcsardi ! 

I'm not sure if this is helpful at all. I have a package failing UBSAN tests and from the output here: https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/tfevents/00check.log

It looks like this is now running under Fedora 36 and clang 16. I couldn't reproduce the problems under Ubuntu because it looks like there might be some ABI compatibility issues with Ubuntu packages (probably built with an older compiler) and clang 15.  

```
* using log directory ‘/data/gannet/ripley/R/packages/tests-clang-SAN/tfevents.Rcheck’
* using R Under development (unstable) (2023-02-15 r83845)
* using platform: x86_64-pc-linux-gnu (64-bit)
* R was compiled by
    clang version 16.0.0
    GNU Fortran (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)
* running under: Fedora Linux 36 (Workstation Edition)
* using session charset: UTF-8
* using option ‘--no-stop-on-test-error’
* checking for file ‘tfevents/DESCRIPTION’ ... OK
* this is package ‘tfevents’ version ‘0.0.1’
* package encoding: UTF-8
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package ‘tfevents’ can be installed ... [373s/271s] OK
* used C compiler: ‘clang version 16.0.0’
* used C++ compiler: ‘clang version 16.0.0’
```

**Comment by gaborcsardi** [comment]
@dfalbel Can you show the output with rhub/clang-asan?

**Comment by gaborcsardi** [comment]
I think the issue is that the errors manifest in Rcpp, and Rcpp is not compiled with ASAN/UBSAN, but it is installed from and RSPM binary. If you (re)start the container, and install Rcpp from source, then you'll be able to reproduce it, probably.

Nevertheless, I'll update the compiler.

**Comment by gaborcsardi** [comment]
It would probably make sense to install `LinkingTo` dependencies from source, with the ASAN compiler, before installing the other dependencies.

**Comment by dfalbel** [comment]
Yes, we have a run here: https://github.com/mlverse/tfevents/actions/runs/4254740070/jobs/7401413855
Downloading the logs, I see:

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘tfevents’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/__w/tfevents/tfevents/check/tfevents.Rcheck/00LOCK-tfevents/00new/tfevents/libs/tfevents.so':
  /__w/tfevents/tfevents/check/tfevents.Rcheck/00LOCK-tfevents/00new/tfevents/libs/tfevents.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameEv
Error: loading failed
Execution halted
ERROR: loading failed
```

I think the unvailable symbol is related to ABI incompatibility between a recent clang and gcc. Or maybe something related to `GLIBCXX_USE_CXX11_ABI`.

**Comment by gaborcsardi** [comment]
Yeah, we would probably need to recompile protobuf with libc++. This is the same for Fedora, so we don't win anything with switching to Fedora. CRAN has a locally installed protobuf, compiled with libc++. 

Let me see how difficult it is to build protobuf...

**Comment by gaborcsardi** [comment]
I can't compile protobuf with clang 16. :(

**Comment by dfalbel** [comment]
Ohh I see, I didn't think they had their own protobuf build. Taught they were using Fedora's protobuf package, and just by being compiled with a more recent compiler it would be compatible. Do they also build other external deps?

Thank you very much! No worries, I *think* i was able to fix the error using the CRAN log only and re-submitted. I can spend more time if the issue still persists.

**Comment by gaborcsardi** [comment]
OK, I managed to compile an older version of the CPP protobuf library. 

Also, we do need to recompile `LinkingTo` packages (Rcpp in this case), and if other packages are `LinkingTo` these, then those as well, and so on. So in this case reticulate and RcppTOML as well. 

Then I can reproduce CRAN exactly.

**Comment by gaborcsardi** [comment]
This is not deployed. We also install the packages from source now. This is not strictly necessary for packages without a `LinkingTo` dependency (on either side), but it is simplest for now.

**Comment by dfalbel** [comment]
Thank ou very much @gaborcsardi ! This really helped a lot!
