### ISSUE TITLE
rchk container

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/containers#29]
This one is tricky, because we need to keep the sources around, both for R and the package(s) we want to check. 

We also need the wllvm Python package, which is not packaged for Ubuntu, so ideally we would install it together with R.

It does not seem important to use R-devel for this, so we could use R-release and Ubuntu 22.04, and binary packages, except for the packages we want to check.

C code from one package may call C code from another package, but I don't know if rchk handles this situation. If it does then `LinkingTo` packages should be also installed from source, with `wllvm`.

In general we don't actually need to install the dependencies of the checked package, only the `LinkingTo` dependencies, and their dependencies. This should work for most packages, but in case it does not we should fall back to the full (hard) dependency install. This is how it is done in the original rchk container: https://github.com/kalibera/rchk/blob/fbde173a84809e8159e50bdc6a03e12119634594/scripts/utils.r#L76

**Comment by krlmlr** [comment]
I see it in https://r-hub.github.io/containers/, is this done now?

Thanks for providing it!

**Comment by gaborcsardi** [comment]
Yeah, it worked well for me.
