### ISSUE TITLE
Installing packages on the 'atlas' container fails

### ISSUE THREAD

**Issue by dfalbel** [r-hub/containers#39]
I see messages like:

```
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'https://raw.githubusercontent.com/r-hub/repos/main/fedora-36/4.4/src/contrib/ps_1.7.5_b1_R4.4_x86_64-pc-linux-gnu-fedora-36.tar.gz'
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 0 != reported length 0
2: In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL 'https://raw.githubusercontent.com/r-hub/repos/main/fedora-36/4.4/src/contrib/ps_1.7.5_b1_R4.4_x86_64-pc-linux-gnu-fedora-36.tar.gz': HTTP status was '404 Not Found'
```

setting `options(repos=)` to a valid CRAN repository fixed the problem, but this seems unexpected.

Edit: Sorry if this is not yet supposed to work . I just noticed this is actually work in progress :)

**Comment by gaborcsardi** [comment]
You need to use pak to install packages. Or, you can use `install.packages()` but then there are no binaries and you need to specify `repos` explicitly. Or set `options(repos)`.

**Comment by dfalbel** [comment]
Thanks! I guess, I was using the containers the wrong way by just `docker run -it` and installing packages from source directly.

**Comment by gaborcsardi** [comment]
It is perfectly fine to use them like that. But the repo at https://raw.githubusercontent.com/r-hub/repos/main/fedora-36/4.4/ only works with pak, so either remove it from `options(repos)`, or specify `repos` explicitly.
