### ISSUE TITLE
Ubuntu containers and linking libdeflate

### ISSUE THREAD

**Issue by theAeon** [r-hub/containers#47]
I've been having a consistent issue on all of the ubuntu containers with the exception of release and next. My in-development package grabs its LDFLAGS from `R CMD --ldflags` which, in this case, contains `-ldeflate`. This would not be an issue if it were not for debian only packaging libdeflate.so.0 in the installed libdeflate package. For some reason, the libdeflate.so symlink is only installed if libdeflate-dev is installed as well. This consistently fixes the issue.

**Comment by gaborcsardi** [comment]
Thanks! The builds seem to be fine now, do you think this is still an issue? If yes, what exactly is the problem? How can we reproduce it?

**Comment by theAeon** [comment]
They seem to be working now (at least on linux)
