### ISSUE TITLE
ubuntu-clang and libstdc++

### ISSUE THREAD

**Issue by theAeon** [r-hub/containers#48]
ubuntu-clang causes Rcpp to fail upon `#include <cmath>`. A bit of research showed that clang searches for the libstdc include directory based on the newest installed gcc, which in this case is 12. While (I think) the libstdc++11 headers are installed, the libstdc++12 headers are not. This is easily resolved by adding the libstdc++-12-dev package-or probably by removing gcc-12.

**Comment by gaborcsardi** [comment]
Thanks! We cannot remove gcc-12, because gfortran-12 needs it. But installing libstdc++-12-dev seems to solve the issue.
