### ISSUE TITLE
set env MKLROOT in intel/mkl containers

### ISSUE THREAD

**Issue by theAeon** [r-hub/containers#49]
Autodetect scripts written by Intel use this environment variable to determine where MKL is in the absence of a configuration argument. It would be ideal to set this for containers in which MKL is expected to be used.

edit: probably easiest way to accomplish this is to source /opt/intel/oneapi/mkl/latest/env/vars.sh

**Comment by gaborcsardi** [comment]
Would you like to submit a PR? (No pressure.)
