### ISSUE TITLE
Provide intel-2024 container

### ISSUE THREAD

**Issue by krlmlr** [r-hub/containers#68]
We're seeing weird errors in duckdb and igraph regarding `get_temporary_buffer()`:

- duckdb: https://www.stats.ox.ac.uk/pub/bdr/Intel/duckdb.out, https://www.stats.ox.ac.uk/pub/bdr/Intel/duckdb.log
- igraph: https://www.stats.ox.ac.uk/pub/bdr/Intel/igraph.out, https://www.stats.ox.ac.uk/pub/bdr/Intel/igraph.log

These don't reproduce in the existing intel container which has the 2023.2 compiler: 

- duckdb: https://github.com/duckdb/duckdb-r/actions/runs/9676877366/job/26697397210
- igraph: https://github.com/igraph/rigraph/actions/runs/9757793671/job/26930945580

Can we upgrade the compiler, or should this be a new container?

**Comment by gaborcsardi** [comment]
Yeah, we should update the version.

**Comment by gaborcsardi** [comment]
Sadly, the container is too big now, an we can't build it on GHA: https://github.com/r-hub/containers/actions/runs/9792014055/job/27036965641#step:7:2135

**Comment by gaborcsardi** [comment]
I fixed the build, so the new container is now deployed.

**Comment by krlmlr** [comment]
Thanks, running now:

- duckdb: https://github.com/duckdb/duckdb-r/actions/runs/9834536464
- igraph: https://github.com/igraph/rigraph/actions/runs/9834559976

**Comment by krlmlr** [comment]
Curious, what did you do to fix the build? Wipe out even more on the GHA machine?

**Comment by krlmlr** [comment]
This still seems to use 2023.2.1? What am I doing wrong?

https://github.com/duckdb/duckdb-r/actions/runs/9834536464/job/27146520243#step:4:509

I ran:

```r
rhub::rhub_check(platforms = rhub::rhub_platforms()$name, branch = "cran-1.0.0-1")
```

**Comment by gaborcsardi** [comment]
> Curious, what did you do to fix the build? Wipe out even more on the GHA machine?

Yeah.

> This still seems to use 2023.2.1? What am I doing wrong?

Ah, the image has now multiple compilers, and the old one is the default. Fixing now.

**Comment by gaborcsardi** [comment]
@krlmlr OK, try again now, it seems to be good now:
https://r-hub.github.io/containers/containers.html#intel
