### ISSUE TITLE
Prevent intel's ifx Fortran compiler from generating interface files

### ISSUE THREAD

**Issue by DavidRConnell** [r-hub/containers#71]
## Issue

By default Intel's Fortran compiler generates interface files for reference purposes only. These may contain non-portable use of `KIND` (i.e. `REAL(KIND=8)`). `R CMD check` detects these files as non-portable and gives a warning.

## Solution

As mentioned by Ivan Krylov on [R-pkg-devel](https://stat.ethz.ch/pipermail/r-package-devel/2024q3/011035.html), ifx accepts the flag `-nogen-interfaces` that prevents the creation of these files and is used in CRAN's intel environment (https://svn.r-project.org/R-dev-web/trunk/CRAN/QA/BDR/gannet/Intel/config.site). Adding this flag to `FFLAGS` in the intel container somewhere will prevent the extraneous warning that causes github actions to mark the check as a failure. Possibly add it to `/root/.R/Makevars`?

**Comment by gaborcsardi** [comment]
Should be fixed in tomorrow's builds.

**Comment by gaborcsardi** [comment]
Actually, wrong issue.

**Comment by gaborcsardi** [comment]
Should be fixed in tomorrow's build.
