### ISSUE TITLE
clang-asan does not seem to use clang

### ISSUE THREAD

**Issue by pachadotdev** [r-hub/containers#78]
I asked a question and Dirk Schumacher noticed this:

```
* R was compiled by
    gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
    GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
```

**Comment by gaborcsardi** [comment]
It does not really matter what. R was compiled with, what matters is what compiler is installed on the container. See https://r-hub.github.io/containers/containers.html#clang-asan and click on 'Compilers'.

Or try running the container:
```
❯ docker run --platform linux/amd64 ghcr.io/r-hub/containers/clang-asan:latest R CMD config CC
clang-18 -fsanitize=address,undefined -fno-sanitize=float-divide-by-zero -fno-sanitize=alignment -fno-omit-frame-pointer -fsanitize=pointer-overflow -fsanitize-trap=pointer-overflow -fsanitize=signed-integer-overflow
```

**Comment by pachadotdev** [comment]
thanks a lot

I added that here to check with compiler I am using to test https://github.com/pachadotdev/open-redatam/blob/main/.github/workflows/build-rpkg.yml
