### ISSUE TITLE
A killed rchk run shows as a success

### ISSUE THREAD

**Issue by krlmlr** [r-hub/containers#82]
https://github.com/duckdb/duckdb-r/actions/runs/11989640418/job/33426263219#step:6:1266

Line 83 in `rchk.sh` is here: https://github.com/r-hub/containers/blob/main/builder/rchk.sh#L83

Is this as simple as adding `set -e` to the script? And should we perhaps do `if-no-files-found: error` in the workflow, https://github.com/actions/upload-artifact/blob/main/action.yml#L11C3-L11C21 ?

**Comment by gaborcsardi** [comment]
Yeah, probably `set -e` will do it. 

IDK about no check files, e.g. what happens if the package has no compiled code?

**Comment by krlmlr** [comment]
PR added. Will this trigger a rebuild of the container?
